# Generated by Django 5.1.5 on 2025-02-05 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_reservedaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservedAccount',
        ),
    ]
