# Generated by Django 5.1.5 on 2025-02-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_delete_reservedaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='virtual_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
