# Generated by Django 5.1.5 on 2025-02-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_wallet_account_name_wallet_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='nin',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
