# Generated by Django 5.1.5 on 2025-01-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the account'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='url',
            field=models.URLField(blank=True, help_text='Link to the account being sold'),
        ),
    ]
