# Generated by Django 5.1.5 on 2025-02-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_socialaccount_description_socialaccount_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
